Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -66,22 +66,31 @@ jobs:
         acs-report-enable: true
       env:
         GRYPE_OUTPUT_FILE: grype-output.json
+      
     - name: Check if grype-output.json exists
       run: |
         ls -al
-        cat grype-output.json || echo "grype-output.json not found"
-    
+        if [ -f "grype-output.json" ]; then
+          echo "grype-output.json exists"
+        else
+          echo "grype-output.json not found"
+          exit 1
+        fi
+      
+    - name: Display content of grype-output.json
+      run: cat grype-output.json
+      
     - name: Check scan results
       if: ${{ success() }}
       run: |
-        CRITICAL_VULNERABILITIES=$(jq -r '.vulnerabilities[] | select(.severity == "CRITICAL")' grype-output.json)
-        if [ -n "$CRITICAL_VULNERABILITIES" ]; then
+        CRITICAL_VULNERABILITIES=$(cat grype-output.json | jq -r '.vulnerabilities[] | select(.severity == "CRITICAL")')
+         if [ -n "$CRITICAL_VULNERABILITIES" ]; then
           echo "Critical vulnerabilities found:"
           echo "$CRITICAL_VULNERABILITIES"
           exit 1
         else
           echo "No critical vulnerabilities found. Scan passed."
-        fi
+        fi    
 
     - name: Upload Anchore scan SARIF report
       uses: github/codeql-action/upload-sarif@v1
