Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -56,11 +56,7 @@ jobs:
     - name: Run R Script
       run: |
         Rscript matrix.R 
-     
-    #- name: Update Grype Database
-     # run: |
-      #  docker run --rm  anchore/grype db update
-       #  docker run --rm  anchore/grype db status
+         
     - name: Scan current project
       id: scan
       uses: anchore/scan-action@v3.6.4
@@ -70,33 +66,27 @@ jobs:
         acs-report-enable: true
       env:
         GRYPE_OUTPUT_FILE: grype-output.json
+    - name: Check if grype-output.json exists
+      run: |
+        ls -al
+        cat grype-output.json || echo "grype-output.json not found"
     
     - name: Check scan results
+      if: ${{ success() }}
       run: |
         CRITICAL_VULNERABILITIES=$(jq -r '.vulnerabilities[] | select(.severity == "CRITICAL")' grype-output.json)
         if [ -n "$CRITICAL_VULNERABILITIES" ]; then
-        echo "Critical vulnerabilities found:"
-        echo "$CRITICAL_VULNERABILITIES"
-        exit 1
+          echo "Critical vulnerabilities found:"
+          echo "$CRITICAL_VULNERABILITIES"
+          exit 1
         else
-        echo "No critical vulnerabilities found. Scan passed."
+          echo "No critical vulnerabilities found. Scan passed."
         fi
 
     - name: Upload Anchore scan SARIF report
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: ${{ steps.scan.outputs.sarif }}
-        
-    - name: Upload Anchore Image scan SARIF report
-      uses: github/codeql-action/upload-sarif@v1
-      with:
-        sarif_file: ${{ steps.imagescan.outputs.sarif }}
-    
-    - name: Scan current project
-      uses: anchore/scan-action@v3
-      with:
-        path: "."
-        #  ${{ github.workspace }}  
              
     - name: Install Syft
       run: |
